### PR TITLE
Feat/login page [CU-863g3tke4]

### PR DESCRIPTION
**Pull request by 0c370t**

### CODE REVIEW

**Review by bwpikaard — CHANGES_REQUESTED** [review]
Needs formatting, but otherwise beautiful. Also make sure we’re not just throwing a ISR on no account found or something but actually handle the error somehow.

**Comment by 0c370t** [comment]
Note; this needs to use https://github.com/simple-icons/simple-icons instead of a hard-coded Epic Games logo

**Comment by 0c370t** [comment]
Task linked: [CU-863g3tke4 Login Page](https://app.clickup.com/t/863g3tke4)

**Review by bwpikaard — CHANGES_REQUESTED** [review]
Refresh logic.

**Review by gankoji — APPROVED** [review]
LGTM

**Pull request merged**
